### PR TITLE
Better behavior for new messages alert

### LINKED ISSUE #384: "Click to view new message" notification doesn't go anywhere
**Steps to replicate:**
1. As a case manager, I receive a new message from a client
2. I click on the alert in my top nav
3. I click the prompt to view the message

**Expected result:**
I'm taken to the new message in the message stream with my client. 

**Actual result:**
I stay on the list of my clients in an endless loop until I click on the right client. 

new message notification

### PR DESCRIPTION
**Pull request by tmaybe**
If there are only messages from one client, clicking the alert will take you directly to that client's message stream. If there are messages from more than one client, you're taken to the client list.

Also, the number of unread messages are now part of the text of the alert.

Closes #384

### CODE REVIEW

**Comment by glassresistor** [comment]
I think in general the changes look good and am only hesitant if we are slowing down the request and/or adding significant queries,.  @tdooner point about hitting the endpoint every 1s is salient.  I think we can definitely tune that down to ~5sec or slower for a quick solution.

If we have more time we can work a way to keep count of unread messages in a way thats fast to read regularly.  

In terms of testing if we can't test the frontend js then I agree we should have it just take a count for now.

**Comment by tmaybe** [comment]
Thank you! I think that, while the polling may be inefficient, the changes don't make it more inefficient. Merging now.

**Comment by tdooner** [comment]
Agreed, and this is still a hypothetical performance problem. The CPU usage on the web servers is negligible, last time I checked.

When we rewrite it in Rails, we can give ActionCable a shot 😀

**Comment by tmaybe** [comment]
ooh, I was wondering if there was a socket.io for rails :)

**Pull request merged**
